# Font
# font_family      DepartureMono Nerd Font Mono Regular
# bold_font        DepartureMonoNerdFontMono Bold
# italic_font      DepartureMonoNerdFontMono Italic
# bold_italic_font DepartureMonoNerdFontMono BoldItalic
font_size        16.5

# Options
confirm_os_window_close 0

# Window
background_opacity 1.0
window_padding_width 0

# Terminal
term xterm-256color

# Mouse
mouse_hide_wait 0

# Keybindings
map ctrl+v paste_from_clipboard
map shift+enter send_text all \x1b\r

# Cursor
cursor #ebdbb2
cursor_text_color #1c1c1c

# Selection
selection_foreground #ebdbb2
selection_background #504945

# Primary
foreground #ebdbb2
background #1c1c1c

# Normal
color0  #1c1c1c
color1  #cc241d
color2  #98971a
color3  #d79921
color4  #458588
color5  #b16286
color6  #689d6a
color7  #ebdbb2

# Bright
color8  #928374
color9  #fb5944
color10 #b8bb26
color11 #fabd2f
color12 #83a598
color13 #d3869b
color14 #8ec07c
color15 #ebdbb2




# BEGIN_KITTY_FONTS
font_family      family='DepartureMono Nerd Font' postscript_name=DepartureMonoNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
