wallpaper {
  monitor = DP-1
  path = /home/archie/.config/hypr/wallpapers/scanlines-med-2560x1440.png
  fit_mode = cover
}

wallpaper {
  monitor = HDMI-A-1
  path = /home/archie/.config/hypr/wallpapers/scanlines-wide-1920x1080.png
  fit_mode = cover
}
