--###############
--## MONITORS ###
--###############

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60Hz",
    position = "2560x588",
    scale = "1",
    transform = 0,
})

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@60Hz",
    position = "0x240",
    scale = "1",
})

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

local terminal = "kitty"
local fileManager = "thunar"
local menu = "rofi -show drun"

--################
--## AUTOSTART ###
--################

--## ENVIRONMENT VARIABLES ###

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

--####################
--## LOOK AND FEEL ###
--####################

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 5.39,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4.79,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.1,
    bezier = "easeOutQuint",
    style = "popin 87%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.49,
    bezier = "linear",
    style = "popin 87%",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 1.73,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.46,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.03,
    bezier = "quick",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.81,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "easeOutQuint",
    style = "fade",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.5,
    bezier = "linear",
    style = "fade",
})
hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 1.79,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.39,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "zoomFactor",
    enabled = true,
    speed = 7,
    bezier = "quick",
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd("/usr/bin/zen-browser"))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("/usr/bin/discord"))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))

hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("~/.local/bin/rotate-screen"))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("~/.config/hypr/Scripts/swapAudioOutput.sh"))
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("/usr/bin/hyprlock"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("bluetoothctl connect 88:c9:E8:DF:3C:9A"))
hl.bind("XF86DoNotDisturb", hl.dsp.exec_cmd("/usr/bin/hyprlock"))
hl.bind(mainMod .. " + Delete", hl.dsp.exec_cmd("/usr/bin/hyprlock"))

local wsMin, wsMax = 1, 8

-- Step one workspace, clamped to wsMin..wsMax (no wraparound).
local function wsStep(delta, moveWindow)
    return function()
        local ws = hl.get_active_workspace()
        if not ws or ws.special then
            return
        end
        local target = ws.id + delta
        if target < wsMin or target > wsMax then
            return
        end
        if moveWindow then
            hl.dispatch(hl.dsp.window.move({ workspace = target }))
        else
            hl.dispatch(hl.dsp.focus({ workspace = target }))
        end
    end
end

hl.bind(mainMod .. " + up", wsStep(1, true))
hl.bind(mainMod .. " + down", wsStep(-1, true))
hl.bind(mainMod .. " + right", wsStep(1, false))
hl.bind(mainMod .. " + left", wsStep(-1, false))
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + mouse_down", wsStep(1, false))
hl.bind(mainMod .. " + mouse_up", wsStep(-1, false))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + RETURN", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + RETURN", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + BACKSPACE", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + BACKSPACE", hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind(mainMod .. " + S", hl.dsp.exec_cmd("~/.config/hypr/Scripts/screenshot.sh"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_cmd("~/.config/hypr/Scripts/annotate-last.sh"))

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pamixer -i 5"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pamixer -d 5"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pamixer -t"))

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "DP-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "3",
    monitor = "DP-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "4",
    monitor = "DP-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "5",
    monitor = "HDMI-A-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "6",
    monitor = "HDMI-A-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "7",
    monitor = "HDMI-A-1",
    persistent = true,
})

hl.workspace_rule({
    workspace = "8",
    monitor = "HDMI-A-1",
    persistent = true,
})

hl.bind(mainMod .. " + Home", hl.dsp.exec_cmd("~/.local/bin/switch-profile"))
hl.config({
    general = {
        gaps_in = 1,
        gaps_out = 0,
        border_size = 0,
        -- https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
        col = {
            active_border = "rgb(928374)",
            inactive_border = "rgb(928374)",
        },
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
    },
    -- https://wiki.hypr.land/Configuring/Variables/#decoration
    decoration = {
        shadow = {
            enabled = false,
            range = 3,
            render_power = 1,
            color = "rgb(093809)",
        },
        -- https://wiki.hypr.land/Configuring/Variables/#blur
        blur = {
            enabled = false,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
    -- https://wiki.hypr.land/Configuring/Variables/#animations
    animations = {
        enabled = true,
        -- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
        --        NAME,           X0,   Y0,   X1,   Y1
        --           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    },
    -- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
    -- "Smart gaps" / "No gaps when only"
    -- uncomment all if you wish to use that.
    -- workspace = w[tv1], gapsout:0, gapsin:0
    -- workspace = f[1], gapsout:0, gapsin:0
    -- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
    -- windowrule = rounding 0, floating:0, onworkspace:w[tv1]
    -- windowrule = bordersize 0, floating:0, onworkspace:f[1]
    -- windowrule = rounding 0, floating:0, onworkspace:f[1]
    -- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
    dwindle = {
        preserve_split = true, -- You probably want this
    },
    -- See https://wiki.hypr.land/Configuring/Master-Layout/ for more
    master = {
        new_status = "master",
    },
    misc = {
        force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
        -- Lets a fresh hyprlock re-attach to an orphaned session lock instead of
        -- leaving the session stranded if the locker ever dies unexpectedly.
        allow_session_lock_restore = true,
    },
    --############
    --## INPUT ###
    --############
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "caps:escape_shifted_capslock",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
    -- Example per-device config
    --##################
    --## KEYBINDINGS ###
    --##################
    -- Apps
    -- Workflow
    -- Move Focus
    -- Move Window to Other Monitor
    -- Scroll through different windows
    -- View different workspaces
    -- Move and Resize Windows
    -- Screenshot
    -- Media Controls
    --#############################
    --## WINDOWS AND WORKSPACES ###
    --#############################
})

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprlock")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("waybar")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("mako")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("python3 ~/p/c/ZenHomepage/server.py")
    hl.exec_cmd("~/.config/hypr/Scripts/speakerconnect.sh")
    hl.exec_cmd("~/.config/scripts/mount-servers.sh")
end)

